version: "3.8"

services:
  app:
    image: app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # Comment this if you are running in production
      - ./frontend/:/home/node/app
      - /home/node/app/node_modules

    # Comment this if you are running in production
    command: ["npm", "run", "dev"]

    # Uncomment this if you are running in production
    # command: [ "npm", "run", "build" ]

    stop_signal: SIGINT

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    expose:
      - 443

  # Comment this if you are use ngrok and running in production
  ngrok-api:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok-api.yml
    volumes:
      - ./ngrok-api.yml:/etc/ngrok-api.yml
    expose:
      - 443

  # Comment this if you are running in production
  fake-api:
    image: fake-api
    build:
      context: ./fake-api
      dockerfile: Dockerfile
    restart: always
    command: ["npx", "json-server", "db.json"]
    ports:
      - "3000:3000"

# Comment this if you are running in production
volumes:
  node_modules_volume:
