version: "3.3"

services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: "/home/node/app"
    volumes:
      # Uncomment this if you are running in development
      - ./frontend/:/home/node/app
      - node_modules_volume:/home/node/app/node_modules

    # Uncomment this if you are running in development
    command: ["npm", "run", "dev"]

    # Uncomment this if you are running in production
    # command: [ "npm", "run", "build" ]

    stop_signal: SIGINT

  # Uncomment this if you are use ngork and running in development
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    expose:
      - 443

# Uncomment this if you are running in development
volumes:
  node_modules_volume:
